boxOpenInfoData = {}
boxOpenInfoData[1] = {awardId=1,awardContent="1000元宝",awardIcon="props_037",awardChest=1,awardDesc="货真价实的1000元宝,10倍增值。"}
boxOpenInfoData[2] = {awardId=2,awardContent="宇智波鼬忍魂*1",awardIcon="props_135",awardChest=1,awardDesc="宇智波鼬忍魂*1，50个忍魂可以合成一张宇智波鼬忍者卡。"}
boxOpenInfoData[3] = {awardId=3,awardContent="万里挑一",awardIcon="props_121",awardChest=1,awardDesc="万里挑一的机会，有概率五星忍者卡，保底四星忍者。"}
boxOpenInfoData[4] = {awardId=4,awardContent="四星武器包",awardIcon="props_029",awardChest=1,awardDesc="有概率获得五星武器卡,较大概率获得四星武器卡,保底三星武器。"}
boxOpenInfoData[5] = {awardId=5,awardContent="四星防具包",awardIcon="props_043",awardChest=1,awardDesc="有概率获得五星防具卡,较大概率获得四星防具卡,保底三星防具。"}
boxOpenInfoData[6] = {awardId=6,awardContent="四星饰品包",awardIcon="props_046",awardChest=1,awardDesc="有概率获得五星饰品卡,较大概率获得四星饰品卡,保底三星饰品。"}
boxOpenInfoData[7] = {awardId=7,awardContent="四星忍术包",awardIcon="props_028",awardChest=1,awardDesc="有概率获得五星忍术卡,较大概率获得四星忍术卡,保底三星忍术。"}
boxOpenInfoData[8] = {awardId=8,awardContent="海量银子8万两",awardIcon="props_036",awardChest=1,awardDesc="海量的银子，80000两白银。"}
boxOpenInfoData[9] = {awardId=9,awardContent="大量银子2万两",awardIcon="props_036",awardChest=1,awardDesc="大量的银子，20000两白银。"}
boxOpenInfoData[10] = {awardId=10,awardContent="尾兽印记碎片*5",awardIcon="props_133",awardChest=1,awardDesc="随机尾兽印记碎片5个。"}
boxOpenInfoData[11] = {awardId=11,awardContent="一乐拉面(大)*6",awardIcon="props_017",awardChest=1,awardDesc="大一乐拉面6个。"}
boxOpenInfoData[12] = {awardId=12,awardContent="兵粮丸(大)*10",awardIcon="props_012",awardChest=1,awardDesc="大兵粮丸10个。"}
boxOpenInfoData[13] = {awardId=13,awardContent="奖励翻倍",awardIcon="props_134",awardChest=1,awardDesc="下次开启该宝箱的奖励翻倍。"}
boxOpenInfoData[14] = {awardId=14,awardContent="500元宝",awardIcon="props_037",awardChest=2,awardDesc="货真价实的500元宝，还等什么。"}
boxOpenInfoData[15] = {awardId=15,awardContent="宇智波鼬忍魂*1",awardIcon="props_135",awardChest=2,awardDesc="宇智波鼬忍魂*1，50个忍魂可以合成一张宇智波鼬忍者卡。"}
boxOpenInfoData[16] = {awardId=16,awardContent="千里挑一",awardIcon="props_132",awardChest=2,awardDesc="千里挑一的机会，大概率四星忍者，保底三星忍者卡。"}
boxOpenInfoData[17] = {awardId=17,awardContent="金钥匙一把",awardIcon="props_129",awardChest=2,awardDesc="可以用来开启黄金宝箱的钥匙。"}
boxOpenInfoData[18] = {awardId=18,awardContent="三星武器",awardIcon="props_041",awardChest=2,awardDesc="有概率获得四星武器卡,较大概率获得三星武器卡,保底二星武器。"}
boxOpenInfoData[19] = {awardId=19,awardContent="三星防具",awardIcon="props_042",awardChest=2,awardDesc="有概率获得四星防具卡,较大概率获得三星防具卡,保底二星防具。"}
boxOpenInfoData[20] = {awardId=20,awardContent="三星饰品",awardIcon="props_047",awardChest=2,awardDesc="有概率获得四星饰品卡,较大概率获得三星饰品卡,保底二星饰品。"}
boxOpenInfoData[21] = {awardId=21,awardContent="三星忍术",awardIcon="props_028",awardChest=2,awardDesc="有概率获得四星忍术卡,较大概率获得三星忍术卡,保底二星忍术。"}
boxOpenInfoData[22] = {awardId=22,awardContent="海量银子3万两",awardIcon="props_036",awardChest=2,awardDesc="海量的银子，30000两白银。"}
boxOpenInfoData[23] = {awardId=23,awardContent="大量银子1.5万两",awardIcon="props_036",awardChest=2,awardDesc="大量的银子，15000两白银。"}
boxOpenInfoData[24] = {awardId=24,awardContent="尾兽印记碎片*3",awardIcon="props_133",awardChest=2,awardDesc="随机尾兽印记碎片3个。"}
boxOpenInfoData[25] = {awardId=25,awardContent="一乐拉面(大)*3",awardIcon="props_017",awardChest=2,awardDesc="大一乐拉面3个。"}
boxOpenInfoData[26] = {awardId=26,awardContent="兵粮丸(大)*5",awardIcon="props_012",awardChest=2,awardDesc="大兵粮丸5个。"}
boxOpenInfoData[27] = {awardId=27,awardContent="奖励翻倍",awardIcon="props_134",awardChest=2,awardDesc="下次开启该宝箱的奖励翻倍。"}
boxOpenInfoData[28] = {awardId=28,awardContent="100元宝",awardIcon="props_037",awardChest=3,awardDesc="货真价实的100元宝。"}
boxOpenInfoData[29] = {awardId=29,awardContent="银钥匙一把",awardIcon="props_128",awardChest=3,awardDesc="可以用来开启白银宝箱的钥匙。"}
boxOpenInfoData[30] = {awardId=30,awardContent="银子5000两",awardIcon="props_036",awardChest=3,awardDesc="银子5000量。"}
boxOpenInfoData[31] = {awardId=31,awardContent="拉面(小)*3",awardIcon="props_016",awardChest=3,awardDesc="小拉面3个。"}
boxOpenInfoData[32] = {awardId=32,awardContent="兵粮丸(小)*3",awardIcon="props_011",awardChest=3,awardDesc="小兵粮丸3个。"}
boxOpenInfoData[33] = {awardId=33,awardContent="奖励翻倍",awardIcon="props_134",awardChest=3,awardDesc="下次开启该宝箱的奖励翻倍。"}
