require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
require("LuaXml")
require("CommonDialogView")
require("ui_layer/ui_accumulateMoneyLayer")
require("ui_layer/ui_accumulateMoneyTableCell")
require("config/firstpurchase_config")
require("ui_layer/ui_purchaseLayer")
require("ui_layer/ui_purchaseTableCell")

function initAccumulateMoney()
	local activityView = GetActivityView()
	local contentNode = activityView:GetNodeContent()
	local ui_accMoney = createObj(ui_accumulateMoneyLayer)
	contentNode:addChild(ui_accMoney.node_)
end

xpcall(initAccumulateMoney, __G__TRACKBACK__)