require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
--require("RLRequest")
require("LuaXml")
require("CommonDialogView")
require("config/activity_config")
require("ui_layer/ui_activityPopupTableCell")
require("ui_layer/ui_activityPopupLayer")

function initactivityPopupLayer()
	local activityPopupLayer = createObj(ui_activityPopupLayer)
	GetMainMenu():GetModelLayer():addChild(activityPopupLayer.node_)
end
--init()
--xpcall(init, __G__TRACKBACK__)