require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
require("RLRequest")
require("LuaXml")
require("CommonDialogView")
require("config/firstpurchase_config")
require("ui_layer/ui_firstMoneyAward")
require("ui_layer/ui_purchaseLayer")
require("ui_layer/ui_purchaseTableCell")

function initFirstAward()
	local activityView = GetActivityView()
	local contentNode = activityView:GetNodeContent()
	local firstMoneyAwardLayer = createObj(ui_firstMoneyAward)
	contentNode:addChild(firstMoneyAwardLayer.node_)
end

xpcall(initFirstAward, __G__TRACKBACK__)