require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
require("RLRequest")
require("LuaXml")
require("CommonDialogView")
require("config/firstpurchase_config")
require("ui_layer/ui_growthfundLayer")
require("ui_layer/ui_growthfundCell")
require("ui_layer/ui_purchaseLayer")
require("ui_layer/ui_purchaseTableCell")

function initGrowthfundLayer()
	local activityView = GetActivityView()
	local contentNode = activityView:GetNodeContent()
	local growthfundlayer = createObj(ui_growthfundLayer)
	contentNode:addChild(growthfundlayer.node_)
end

xpcall(initGrowthfundLayer, __G__TRACKBACK__)