require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
require("LuaXml")
require("CommonDialogView")
require("ui_layer/ui_levelRankLayer")
require("ui_layer/ui_levelRankTableCell")
require("ui_layer/ui_levelRankGiftTableCell")

function initLevelRank()
	local activityView = GetActivityView()
	local contentNode = activityView:GetNodeContent()
	local ui_levelRank = createObj(ui_levelRankLayer)
	contentNode:addChild(ui_levelRank.node_)
end

xpcall(initLevelRank, __G__TRACKBACK__)