require("RLRequest")
require("util/protocol")
require("util/tools")
require("util/common")
require("global/cfg")
require("util/localizable")
require("ui_common/node_base_t")
require("ui_common/layer_base_t")
require("LuaXml")
require("CommonDialogView")
require("ui_layer/ui_limitedGroupBuyingLayer")
require("ui_layer/ui_limitedGroupBuyTableCell")
require("config/firstpurchase_config")
require("ui_layer/ui_purchaseLayer")
require("ui_layer/ui_purchaseTableCell")

function init()
	local activityView = GetActivityView()
	local contentNode = activityView:GetNodeContent()
	local ui_LmtGrpBuy = createObj(ui_limitedGroupBuyingLayer)
	contentNode:addChild(ui_LmtGrpBuy.node_)
end

xpcall(init, __G__TRACKBACK__)